version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    network_mode: "host"
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - /var/lib/postgresql/data:/data/postgres
    env_file:
      - docker.env